### PR TITLE
course: task 4.1 decimal calculator

### PR DESCRIPTION
**Pull request by BorislavAnchev**
The decimal calculator task.

### CODE REVIEW

**Comment by mgenov** [comment]
Doesn't look like it belongs to build tools tasks.

**Comment by BorislavAnchev** [comment]
I put it here since it's from Topic 4 - Test Driven Development and it has requirements to be packaged with WebPack and tested with Karma Runner.

**Comment by mgenov** [comment]
Added testing repository for these tasks: https://github.com/clouway-incubator/borislav-testing

**Comment by BorislavAnchev** [comment]
I guess I should upload there only the Decimal Calculator, since the Counter is already reviewed?

**Comment by mgenov** [comment]
Yes, you have to rebase your branch properly to be able to create a PR for the Decimal Calculator.

**Pull request closed without merging**
